version: '3.8'

services:
  layzomarket-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5058:5058"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5058"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.layzomarket.rule=Host(`layzomarket.yourdomain.com`)"
      - "traefik.http.routers.layzomarket.tls=true"
      - "traefik.http.routers.layzomarket.tls.certresolver=letsencrypt"
      - "traefik.http.services.layzomarket.loadbalancer.server.port=5058"

  # Optional: Add Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@yourdomain.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped

volumes:
  letsencrypt: